version: '3.8'

services:
  db:
    image: mysql:8.0.31
    ports:
      - 3306:3306
    volumes:
      - youtube-db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  backend:
    build: ./backend/
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "cd app && npm start"
    ports:
      - 3001:3000

volumes:
  youtube-db-store:
