name: run rspec

on:
  push:
  workflow_dispatch:

env:
  RAILS_ENV: test
  DATABASE_HOST: 127.0.0.1

jobs:
  rspec:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: backend
    services:
      mysql:
        image: mysql:8.0.29
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
    steps:
      - uses: actions/checkout@v3
      - name: set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: backend
      - name: set up database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
      - name: run migration
        run: |
          ls
          bundle exec rails db:migrate
      - name: run rspec
        run: bundle exec rspec
